### ISSUE TITLE
Ors components remove underline text decoration on hover

### ISSUE THREAD

**Issue by einarhuseby** [FNLF/fnlf-client#313]
The underline text decoration on the panel heading title is annoying and clutters the interface.

Using app.css and overriding bootstrap default as:
```css
.panel-title > a,
.panel-title > small,
.panel-title > .small,
.panel-title > small > a,
.panel-title > .small > a {
  text-decoration: none!important;
}
```
